packages:
  - packages/*

packageExtensions:
  # Force chakra package to use specific @types/react version
  "@chakra-ui/react@*":
    dependencies:
      "@types/react": "19.1.12"

publicHoistPattern:
  - '@vue/compiler-dom'

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
