packages:
  - packages/*

packageExtensions:
  "@chakra-ui/react@*":
    dependencies:
      "@types/react": "19.1.12"
  "mui":
    dependencies:
      "jsdom": "26.1.0"

publicHoistPattern:
  - "@vue/compiler-dom"

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - vue-demi
