packages:
  - packages/*

packageExtensions:
  "mui":
    dependencies:
      "jsdom": "26.1.0"

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - carbon-components-svelte
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - vue-demi
