name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Test and build only affected packages
  test-and-build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
          run_install: false

      - name: Use Node.js 22.x 
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies for affected packages
        run: bash install-scope.sh

      - name: Lint affected packages
        run: |
          bash turbo-scope.sh lint

      - name: Run tests on affected packages
        run: |
          bash turbo-scope.sh test

      - name: Build affected packages
        run: |
          bash turbo-scope.sh build

  # Full build on main branch (on demand)
  full-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run full test suite
        run: pnpm run test

      - name: Build all packages
        run: pnpm run build
